apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-mariadb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-mariadb
  template:
    metadata:
      labels:
        app: core-mariadb
    spec:
      containers:
        - name: core-mariadb
          image: mariadb
          env:
          - name: MARIADB_ROOT_PASSWORD
            value: "123456"
          - name: MYSQL_ROOT_PASSWORD
            value: "mipass"
          - name: MYSQL_DATABASE
            value: "database_development"  
---
apiVersion: v1
kind: Service
metadata:
  name: core-mariadb-srv
spec:
  selector:
    app: core-mariadb
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
