apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: home
          image: home
          imagePullPolicy: Never
          env:
          - name: APP_PORT
            value: "3000"
          - name: MONGO_HOST
            value: "home-mongo-srv"
          - name: MONGO_PORT
            value: "27017"
          - name: NATS_HOST
            value: "nats-srv"
          - name: NATS_PORT
            value: "4222"            
---
apiVersion: v1
kind: Service
metadata:
  name: home-srv
spec:
  selector:
    app: home
  ports:
    - name: home
      protocol: TCP
      port: 3000
      targetPort: 3000